# Generated by Django 4.0.4 on 2022-06-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('id_duenio', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
