# Generated by Django 4.0.4 on 2022-06-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('duenio', models.CharField(max_length=50)),
                ('tecnico', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('tiempo', models.IntegerField()),
                ('llegada', models.DateField()),
                ('entrega', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Mantenimiento',
        ),
    ]
