# Generated by Django 4.0.4 on 2022-06-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_bicicleta_delete_mantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='modelo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
