# Generated by Django 4.0.4 on 2022-06-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_bicicleta_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
