# Generated by Django 4.0.4 on 2022-06-07 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_bicicleta_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
