# Generated by Django 4.0.4 on 2022-06-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_delete_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='duenio',
            field=models.CharField(max_length=50, verbose_name='Dueño'),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='entrega',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='llegada',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='modelo',
            field=models.CharField(max_length=50, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='tecnico',
            field=models.CharField(max_length=50, verbose_name='Tecnico a cargo'),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='tiempo',
            field=models.IntegerField(verbose_name='Dias de mantenimiento'),
        ),
    ]
