# Generated by Django 4.0.4 on 2022-06-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_bicicleta_duenio_alter_bicicleta_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='entrega',
            field=models.DateField(default=None, null=True),
        ),
    ]
