# Generated by Django 4.0.4 on 2022-06-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_alter_bicicleta_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duenio',
            fields=[
                ('id_duenio', models.AutoField(primary_key=True, serialize=False)),
                ('nom_duenio', models.CharField(max_length=50, verbose_name='Dueño')),
            ],
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
