# Generated by Django 4.0.4 on 2022-06-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_duenio_alter_bicicleta_entrega'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Duenio',
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='duenio',
            field=models.CharField(max_length=50, verbose_name='Duenio'),
        ),
    ]
