# Generated by Django 4.0.4 on 2022-06-07 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_duenio_alter_bicicleta_duenio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.CharField(max_length=50, verbose_name='Tecnico a cargo')),
            ],
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.tecnico'),
        ),
    ]
