# Generated by Django 4.0.4 on 2022-06-07 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_tecnico_alter_bicicleta_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
            ],
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.marca'),
        ),
    ]
