# Generated by Django 4.0.4 on 2022-06-07 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_marca_alter_bicicleta_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
            ],
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='modelo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='aplicacion.modelo'),
            preserve_default=False,
        ),
    ]
