# Generated by Django 4.0.4 on 2022-06-07 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_modelo_alter_bicicleta_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='modelo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='aplicacion.modelo'),
            preserve_default=False,
        ),
    ]
