# Generated by Django 4.0.4 on 2022-06-07 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0014_marca_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='modelo',
        ),
    ]
