# Generated by Django 4.0.4 on 2022-06-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0015_remove_marca_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='modelo',
            field=models.CharField(max_length=50, null=True, verbose_name='Modelo'),
        ),
    ]
